name: Streamlit App Deployment with Ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # نسخه پایتون مورد نیاز

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit pyngrok  # نصب Streamlit و Ngrok

    - name: Run Streamlit App with Ngrok
      run: |
        nohup streamlit run main.py --server.port 8501 &
        sleep 10
        python -m pyngrok http 8501 > ngrok_output.txt &
        sleep 10
        cat ngrok_output.txt
        
    - name: Display Ngrok Public URL
      run: |
        NGROK_URL=$(grep -o 'https://[0-9a-z]*\.ngrok.io' ngrok_output.txt | head -1)
        echo "Your Streamlit app is live at: $NGROK_URL"
