name: Streamlit App Deployment with Ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit pyngrok

    - name: Run Streamlit App in Background
      run: |
        nohup streamlit run main.py --server.port 8501 > streamlit_output.log 2>&1 &
        sleep 10  # صبر برای اجرای Streamlit

    - name: Start Ngrok and Get URL
      run: |
        python -c "
from pyngrok import ngrok
public_url = ngrok.connect(8501, bind_tls=True)
print(f'NGROK_URL: {public_url.public_url}')
with open('ngrok_output.txt', 'w') as f:
    f.write(public_url.public_url)
"
        sleep 5  # صبر برای اطمینان از ذخیره لینک

    - name: Display Ngrok URL
      run: |
        echo "============ NGROK OUTPUT ============"
        cat ngrok_output.txt || echo 'Ngrok output file not found!'
        echo "======================================"
